# Generated by Django 3.2.8 on 2021-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakuSuke',
            fields=[
                ('takusukeID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('member', models.CharField(blank=True, max_length=500)),
                ('submitDate', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('CREATE', 'クリエイト'), ('EDIT', 'エディット'), ('SUBMIT', 'サブミット')], max_length=50)),
            ],
        ),
    ]
