# Generated by Django 3.2.8 on 2021-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_takusuke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takusuke',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATE', 'クリエイト'), ('EDIT', 'エディット'), ('SUBMIT', 'サブミット')], max_length=50),
        ),
    ]
